version: 2.1
jobs:
  build:
    docker:
      # Primary container where the job's commands are run
      - image: cimg/go:1.18
      # Any additional containers are started in the same network
      - image: mongo:5.0.6-focal
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: go get ./...
      - run:
          name: Push Config
          command: mkdir -p $HOME/.georacle && . scripts/config-gen.sh > $HOME/.georacle/config.json
      - run:
          name: Run tests
          command: go test -v ./...
